backend:
  name: github
  auth_endpoint: auth
  repo: gabehercules/Portfolio_V2
  branch: master
  site_doamin: gabe-portfolio.netlify.app/

publish_mode: editorial_workflow
media_folder: static/assets/img
public_folder: /assets/img


collections:
    #Projects Collection

  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {label: "Category", name: "category", widget: "select", options: ["UI Design", "Product Design", "Web Design", "Brand Design", "UX Design", "UI/UX"]}
      - {label: "Body", name: "body", widget: "markdown"}